# Generated by Django 2.2.7 on 2019-12-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/cover/')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('pdf', models.FileField(upload_to='books/pdf')),
            ],
        ),
    ]
